# Generated by Django 4.0.4 on 2022-04-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('brand_name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('model_year', models.IntegerField()),
                ('title_status', models.CharField(max_length=150)),
                ('vin_number', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
            ],
            options={
                'ordering': ('model_name',),
            },
        ),
    ]
